apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  type: ClusterIP
  selector:
    app: service1
  ports:
  - name: flask
    port: 5001
    targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  labels:
    app: service1
spec:
  selector:
    matchLabels:
      app: service1
  replicas: 3
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: stratcastor/rand1:build-0
        ports:
          - containerPort: 5001
